const actionType = {
  SELECTED : "SELECTED",
  GET_DATA : "GET_DATA",
  CHANGE_MY_POST : "CHANGE_MY_POST",
  CHANGE_COMPLETED : "CHANGE_COMPLETE",
  CHANGE_STATUS : "CHANGE_STATUS"

}
export default actionType;
